### ISSUE TITLE
default login details

### ISSUE THREAD

**Issue by debonair** [YourTradingSystems/EasyERP#1]
What are the default login details, Please and a readme, for getting started

**Comment by YourTradingSystems** [comment]
@debonair 
default login: admin
default password: 111111

Readme. Comprehensive instructions for getting started are being worked on. These will be published shortly.

To proceed with installations, please download install package from sourceforge: 
http://sourceforge.net/projects/easyerp/files/EasyERP/1.0/

Also database for the project will be published on GitHub.

Best regards.

EasyERP Team

**Comment by debonair** [comment]
I am getting "Such user doesn't registered" when try to login

**Comment by YourTradingSystems** [comment]
We have just now uploaded database. Please download dump.zip from GitHub. Unpack this if Windows to C drive. 
If Linux to user's home directory. 

After this start MongoD service. In another console window start Mongorestore.

eg. MongoDB is installed in C:\MongoDB. To start MongoD service we must type such command in console: 
C:\MongoD\mongod.exe 

For mongo restore:
C:\MongoD\mongorestore.exe 

Main condition: on C drive there has to be a folder data\db

Thanks,

EasyERP Team

**Comment by CreativeWolf** [comment]
Hi,

I downloaded the master.zip from github now how do I use the data dump on linux?

Thank you

**Comment by CreativeWolf** [comment]
I unzipped the dump.zip and from inside the dump folder, I tried the following commands:
mongorestore --dbpath /var/lib/mongodb -db mainDB mainDB
mongorestore --dbpath /var/lib/mongodb -db CRM CRM

I get the following Error when I access the application:

Error: no open connections
    at Db._executeQueryCommand (/srv/bien/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1705:21)
    at Cursor.nextObject (/srv/bien/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:649:13)
    at Collection.findOne (/srv/bien/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/collection.js:1008:10)
    at /srv/bien/node_modules/connect-mongo/lib/connect-mongo.js:186:18
    at MongoStore._get_collection (/srv/bien/node_modules/connect-mongo/lib/connect-mongo.js:126:21)
    at MongoStore.get (/srv/bien/node_modules/connect-mongo/lib/connect-mongo.js:185:10)
    at Object.session [as handle](/srv/bien/node_modules/express/node_modules/connect/lib/middleware/session.js:308:11)
    at next (/srv/bien/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle](/srv/bien/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/srv/bien/node_modules/express/node_modules/connect/lib/proto.js:190:15)

Here's the mongodb.log

2015-11-20T10:43:55.789-0500 [initandlisten] connection accepted from 127.0.0.1:54486 #2 (2 connections now open)
2015-11-20T10:43:55.789-0500 [initandlisten] connection accepted from 127.0.0.1:54487 #3 (3 connections now open)
2015-11-20T10:43:55.793-0500 [initandlisten] connection accepted from 127.0.0.1:54488 #4 (4 connections now open)
2015-11-20T10:43:55.796-0500 [initandlisten] connection accepted from 127.0.0.1:54489 #5 (5 connections now open)
2015-11-20T10:44:55.635-0500 [clientcursormon] mem (MB) res:76 virt:367
2015-11-20T10:44:55.636-0500 [clientcursormon]  mapped:240
2015-11-20T10:44:55.637-0500 [clientcursormon]  connections:5
2015-11-20T10:49:55.741-0500 [clientcursormon] mem (MB) res:78 virt:367
2015-11-20T10:49:55.741-0500 [clientcursormon]  mapped:240
2015-11-20T10:49:55.741-0500 [clientcursormon]  connections:5

Not sure as to what to be done - Please help

Thank you
